### PR TITLE
[TW15475484] Postcard in Accordion Paragraphs

### PR DESCRIPTION
**Pull request by jacine**

### CODE REVIEW

**Comment by zakiya** [comment]
Fantastic. 

Can we also add a form alter to lock down the background color of the nested postcard to Default (None)? Looks no good with light or dark.

**Comment by jacine** [comment]
@zakiya Yeah... I was waiting on tomorrow’s meeting for this, to ask Jesse whether this was a bug or if I should limit it, but I think what you’re suggesting is the best way forward, as I can’t see any other color looking decent in there. 😉

I’m also curious what you think about hiding the field vs disabling it, which I did with the heading.

**Comment by zakiya** [comment]
Let's hide the heading and background fields. (Why are YOU still online? lol)

**Comment by jacine** [comment]
😂

**Pull request merged**
